import time
import json
import os
import pandas as pd  # <--- ADD THIS LINE HERE
import MetaTrader5 as mt5
import logfire
from alpha_agent import FiveBotAlphaCouncil
from risk_agent import AssetRiskGuard, AccountState

# Configure Logfire for live monitoring [1]
logfire.configure(
    token="pylf_v1_eu_zwcrVr8W6Lq9FYfGFLcbP1kr3VmcL6kyJdTqpbZNNhMp",
    console=logfire.ConsoleOptions(min_log_level="notice")
)
logfire.instrument_pydantic()

ALLOWED_ASSETS = [
    "AUDUSD", "EURCHF", "EURGBP", "EURUSD", "GBPUSD", "USDCAD", "USDCHF", "USDJPY",
    "XAGUSD", "XAUUSD",
    "BARUSD", "BTCUSD", "ETHUSD", "SOLUSD", "XRPUSD"
]

SENTIMENT_FILE = "sentiment_regime.json"

def load_sentiment_bias() -> str:
    """Reads the background sentiment file generated by your Northflank cron job [1]."""
    if os.path.exists(SENTIMENT_FILE):
        try:
            with open(SENTIMENT_FILE, "r") as f:
                data = json.load(f)
                return data.get("bias", "NEUTRAL")
        except Exception:
            pass
    return "NEUTRAL"

def execute_mt5_order(symbol: str, action: str, volume: float, price: float, comment: str = ""):
    """Submits a market execution order directly to the MetaTrader 5 terminal [1]."""
    # Map actions to MT5 action types
    order_type = mt5.ORDER_TYPE_BUY if action == "BUY" else mt5.ORDER_TYPE_SELL
    
    request = {
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": symbol,
        "volume": volume,
        "type": order_type,
        "price": price,
        "deviation": 20, # Max slippage allowed in points [1]
        "magic": 123456, # Unique identifier for your bot council [1]
        "comment": comment,
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC, # Immediate-or-Cancel to prevent partial fills [1]
    }
    
    # Send transaction
    result = mt5.order_send(request)
    if result.retcode != mt5.TRADE_RETCODE_DONE:
        logfire.error("MT5 Order Failed", symbol=symbol, action=action, error=result.comment, retcode=result.retcode)
        print(f"❌ MT5 Order Failed for {symbol}: {result.comment}")
    else:
        logfire.notice("MT5 Order Executed Successfully", symbol=symbol, action=action, price=result.price, volume=volume)
        print(f"🎯 Successful {action} order executed on {symbol} at {result.price}")
    return result

def live_trading_loop():
    print("==================================================")
    print("      QUANTBOT METATRADER 5 LIVE ORCHESTRATOR     ")
    print("==================================================")
    
    # 1. Initialize connection to MT5 terminal
    if not mt5.initialize():
        print(f"❌ MT5 Initialization failed: {mt5.last_error()}")
        return
        
    print("✅ Successfully linked to MetaTrader 5 terminal.")
    
    council = FiveBotAlphaCouncil()
    guard = AssetRiskGuard()
    
    # Keep track of active positions locally to avoid redundant API calls
    local_positions = {asset: None for asset in ALLOWED_ASSETS}
    
    try:
        while True:
            # Read global macro sentiment to dynamically skew decision parameters [1]
            sentiment_bias = load_sentiment_bias()
            
            # Apply sentiment skew to Alpha Council thresholds
            if sentiment_bias == "BULLISH":
                # Loosen the threshold to buy, tighten to sell
                council.bot1_threshold = 0.25 
            elif sentiment_bias == "BEARISH":
                council.bot1_threshold = 0.45 
            else:
                council.bot1_threshold = 0.35 # Default
            
            # 2. Sync account balance metrics live with the terminal
            acct = mt5.account_info()
            if acct is None:
                print("⚠️ Failed to fetch live account details from MT5.")
                time.sleep(1)
                continue
                
            # Populate our standard AccountState object
            current_state = AccountState(
                equity=acct.equity,
                used_margin=acct.margin,
                gross_exposure=acct.margin_initial # Proxy or sum of asset exposures
            )
            
            # 3. Process each instrument chronologically
            for symbol in ALLOWED_ASSETS:
                # Fetch tick data live from Symphonix gateway [1]
                tick = mt5.symbol_info_tick(symbol)
                if tick is None:
                    continue
                    
                mid_price = (tick.bid + tick.ask) / 2.0
                council.update_price(symbol, mid_price)
                
                # Check current open positions in MT5 for this asset
                positions = mt5.positions_get(symbol=symbol)
                
                # --- EXIT EVALUATION ---
                if positions:
                    pos = positions[0] # Assume one position per asset for simplicity
                    entry_price = pos.price_open
                    direction = "BUY" if pos.type == mt5.POSITION_TYPE_BUY else "SELL"
                    
                    # Calculate percentage return
                    if direction == "BUY":
                        current_return = (mid_price - entry_price) / entry_price
                    else:
                        current_return = (entry_price - mid_price) / entry_price
                        
                    # Rule-based Profit Target (+0.2%) or Stop Loss (-0.1%) [1]
                    if current_return >= 0.002 or current_return <= -0.001:
                        close_action = "SELL" if direction == "BUY" else "BUY"
                        print(f"🛑 [Exit Signal] Closing {symbol} position...")
                        execute_mt5_order(symbol, close_action, pos.volume, mid_price, comment="Exit Bracket")
                        
                # --- ENTRY EVALUATION ---
                else:
                    # Construct a mock row dictionary to mimic raw data format for your bots
                    mock_row = {
                        'bid': tick.bid,
                        'ask': tick.ask,
                        'book_imbalance': 0.0, # We can replace with live book depth if available [1]
                        'bot1_vote': 'HOLD',
                        'bot2_vote': 'HOLD',
                        'bot3_vote': 'HOLD',
                        'bot4_vote': 'HOLD'
                    }
                    
                    # Since we are live, we compute indicators online or use a fast tick window
                    # Evaluating the Alpha Council decision
                    analysis = council.evaluate_market(mock_row, symbol)
                    signal = analysis.get("signal")
                    
                    if signal in ["BUY", "SELL"]:
                        trade_size_cash = 1000000.0 # Standard size from backtest [1]
                        
                        # Verify safe parameters with the Risk Agent before execution
                        current_time = pd.Timestamp.now()
                        is_safe = guard.validate_trade(current_state, symbol, trade_size_cash, current_time)
                        
                        if is_safe:
                            trade_volume = trade_size_cash / mid_price
                            # Normalize volume to MT5 contract sizes (lot sizes) if needed [1]
                            # For standard Forex, $1,000,000 exposure is roughly 10 standard lots [1]
                            mt5_lot_size = round(trade_volume / 100000, 2) 
                            
                            if mt5_lot_size > 0:
                                print(f"🚀 [Entry Signal] Executing {signal} for {symbol}...")
                                execute_mt5_order(symbol, signal, mt5_lot_size, mid_price, comment="Alpha Council Consensus")
            
            # Control loop frequency to limit processing overhead [1]
            time.sleep(1) 
            
    except KeyboardInterrupt:
        print("\nStopping Live Execution Bridge...")
    finally:
        mt5.shutdown()
        print("MetaTrader 5 connection closed.")

if __name__ == "__main__":
    live_trading_loop()